#       class -----> later -----> object
# x ------------------------------------->
# class vs object

# declare the class
class Product:
    # init function
    # def init( name, price):
    #     p = Product()
    #     p.name  = name 
    #     p.price = price
    #     return p
    def __init__(self, name, price):
        self.name  = name 
        self.price = price

    def printIt(p):
        print("Product", p.name, p.price)

# p1= Product.init("OS", 100)
# p2= Product.init("Antivirus", 50)
# p3= Product.init("Game", 10)
p1= Product("OS", 100)
p2= Product("Antivirus", 50)
p3= Product("Game", 10)
# #create some objects
# p1 = Product() # an ob generated by the scheme of Product class
# p1.name  = "OS" # add property - what is under the package
#                 #property - a variable inside object box
# p1.price = 100

# p2 = Product()
# p2.name = "Antivirus"
# p2.price = 50

# p3 = Product() 
# p3.name = "Game"
# p3.price = 10

Product.printIt(p1)
Product.printIt(p2)
Product.printIt(p3)

